#!/usr/bin/env bash
set -euo pipefail
# debug on
# set -x

# ensure directories
mkdir -p path-discovery-output/ffuf/results

# defaults
THREADS="${FFUF_THREADS:-40}"
FFUF_TIMEOUT="${FFUF_TIMEOUT:-10}"
FOLLOW_FLAG=""
if [ "${FFUF_FOLLOW:-false}" = "true" ] || [ "${FFUF_FOLLOW:-false}" = "True" ]; then
  FOLLOW_FLAG="-r"
fi

STATUS_FILTER=""
if [ -n "${STATUS_CODES:-}" ]; then
  # remove spaces and keep comma-separated list
  CLEAN_CODES=$(echo "${STATUS_CODES}" | tr -d ' ')
  STATUS_FILTER="-mc ${CLEAN_CODES}"
fi

# prepare extension flags for ffuf (-e ext1 ext2)
EXT_FLAG=""
if [ -n "${EXTENSIONS:-}" ]; then
  EXT_CLEAN=$(echo "${EXTENSIONS}" | sed 's/ //g')
  # ffuf expects multiple -e flags or space separated after -e, we'll use -e ext1 -e ext2
  # build -e ext1 -e ext2 form
  IFS=',' read -r -a EXTS_ARR <<< "$EXT_CLEAN"
  for e in "${EXTS_ARR[@]}"; do
    e_trim=$(echo "$e" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
    if [ -n "$e_trim" ]; then
      EXT_FLAG="${EXT_FLAG} -e ${e_trim}"
    fi
  done
fi

TARGETS_FILE="path-discovery-output/ffuf/targets.txt"
if [ ! -s "$TARGETS_FILE" ]; then
  echo "Error: targets file not found or empty: $TARGETS_FILE" >&2
  exit 0   # don't fail the whole job; just nothing to do
fi

while IFS= read -r base || [ -n "$base" ]; do
  # sanify base and create filename-safe name
  name=$(echo "$base" | sed -E 's#https?://##' | sed -E 's#[:/]+#_#g')
  out="path-discovery-output/ffuf/results/ffuf_${name}.json"
  echo "Running ffuf against $base -> $out (threads=${THREADS}, timeout=${FFUF_TIMEOUT})"

  # Run ffuf directly (no nested bash -lc). Keep command robust.
  ffuf -u "${base}/FUZZ" -w wordlists/wordlist.txt -t "${THREADS}" -timeout "${FFUF_TIMEOUT}" -of json ${FOLLOW_FLAG} ${EXT_FLAG} ${STATUS_FILTER} -fw 0 -o "$out" || {
    echo "ffuf returned non-zero for $base (continuing)" >&2
    continue
  }

  # quick processing if ffuf produced output
  if [ -s "$out" ]; then
    # extract urls if jq available
    if command -v jq >/dev/null 2>&1; then
      jq -r '.results[]?.url' "$out" 2>/dev/null | sort -u > "path-discovery-output/ffuf/results/urls_${name}.txt" || true
    fi
  fi
done < "$TARGETS_FILE"